/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.ControladorArbol;
import Modelos.Actividad;
import Modelos.Tablero;
import Modelos.ModeloRegistrarActividad;
import Controladores.ControladorTablero;
import Modelos.Arbol;
import Modelos.GenerarArchivo;
//import Modelos.Jugada;
import Modelos.Nodo;
import Modelos.Pieza;
import Modelos.Posicion;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.concurrent.TimeUnit;
//import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Joaquin
 */
public class TableroGUI extends javax.swing.JFrame{

    /*Variables del tablero*/
    private JLabel[][] casillas = new JLabel[8][8];;
    private final byte TAMANIO = 8;
    public Icon ImageIcon;
    private boolean isSelected = false;
    private boolean isActive = true;
    //private Pieza piezaActiva;
    private String nombrePieza="NoPieza";
    private char equipo; //Tipo de pieza
    public Tablero tablero;
    public Tablero copiaTablero;
    public Arbol arbol;
    //public Nodo nodoRaiz;
    /*variables del Jugador*/
    private String Jugador;
    private char colorJugador;
    private boolean turnoUsuario;
    
    private String[][] margen = {{"H1","H2","H3","H4","H5","H6","H7","H8"},
                                 {"G1","G2","G3","G4","G5","G6","G7","G8"},
                                 {"F1","F2","F3","F4","F5","F6","F7","F8"},
                                 {"E1","E2","E3","E4","E5","E6","E7","E8"},
                                 {"D1","D2","D3","D4","D5","D6","D7","D8"},
                                 {"C1","C2","C3","C4","C5","C6","C7","C8"},
                                 {"B1","B2","B3","B4","B5","B6","B7","B8"},
                                 {"A1","A2","A3","A4","A5","A6","A7","A8"}};
    
    
    /*Variables de Movimientos*/
    private ArrayList<Posicion> movimientosPosibles;
    
    /*Variables de Bitacora de Juego*/
    ModeloRegistrarActividad modeloActividad = new ModeloRegistrarActividad();
    
    /*Variables de controladores*/
    ControladorTablero ctrTablero = new ControladorTablero();
    ControladorArbol ctrArbol = new ControladorArbol();
    //
    String rutaArchivo = "./src/Files/ResumenJuego.txt";
    BufferedWriter bw;
    File archivoResumen = new File(rutaArchivo);
    

    private String jugadas = "";
    private String estadoJuego = "Has ganado"; 
    private boolean finalizo = false;

    /**
     * Creates new form Tablero
     */
    public TableroGUI() {  
        this.Jugador = "";
        initComponents();
        LogJuego.setModel(modeloActividad);
        jLabel1.setVisible(false);
    }
    
    public void agregarComponentes(){
        tablero = new Tablero();
        generarTablero();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TableroJuego = new javax.swing.JPanel();
        panelFichas = new javax.swing.JPanel();
        alfilBlanco = new javax.swing.JLabel();
        caballoBlanco = new javax.swing.JLabel();
        peonBlanco = new javax.swing.JLabel();
        reinaBlanco = new javax.swing.JLabel();
        reyBlanco = new javax.swing.JLabel();
        torreBlanco = new javax.swing.JLabel();
        alfilOscuro = new javax.swing.JLabel();
        caballoOscuro = new javax.swing.JLabel();
        peonOscuro = new javax.swing.JLabel();
        reinaOscuro = new javax.swing.JLabel();
        reyOscuro = new javax.swing.JLabel();
        torreOscuro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        btnJuegoNuevo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LogJuego = new javax.swing.JList<>();
        etJugador = new javax.swing.JLabel();
        labelJugador = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableroJuego.setBackground(new java.awt.Color(0, 153, 153));
        TableroJuego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        TableroJuego.setAlignmentX(0.0F);
        TableroJuego.setAlignmentY(0.0F);
        TableroJuego.setAutoscrolls(true);
        TableroJuego.setPreferredSize(new java.awt.Dimension(800, 800));

        javax.swing.GroupLayout TableroJuegoLayout = new javax.swing.GroupLayout(TableroJuego);
        TableroJuego.setLayout(TableroJuegoLayout);
        TableroJuegoLayout.setHorizontalGroup(
            TableroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        TableroJuegoLayout.setVerticalGroup(
            TableroJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        panelFichas.setBackground(new java.awt.Color(153, 153, 153));
        panelFichas.setPreferredSize(new java.awt.Dimension(345, 150));

        alfilBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alfil.png"))); // NOI18N
        alfilBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        alfilBlanco.setPreferredSize(new java.awt.Dimension(68, 68));
        alfilBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alfilBlancoMouseClicked(evt);
            }
        });

        caballoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caballo.png"))); // NOI18N
        caballoBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        caballoBlanco.setPreferredSize(new java.awt.Dimension(68, 68));
        caballoBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caballoBlancoMouseClicked(evt);
            }
        });

        peonBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peon.png"))); // NOI18N
        peonBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        peonBlanco.setPreferredSize(new java.awt.Dimension(68, 68));
        peonBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peonBlancoMouseClicked(evt);
            }
        });

        reinaBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reina.png"))); // NOI18N
        reinaBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reinaBlanco.setPreferredSize(new java.awt.Dimension(68, 68));
        reinaBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reinaBlancoMouseClicked(evt);
            }
        });

        reyBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rey.png"))); // NOI18N
        reyBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reyBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reyBlancoMouseClicked(evt);
            }
        });

        torreBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/torre.png"))); // NOI18N
        torreBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        torreBlanco.setPreferredSize(new java.awt.Dimension(68, 68));
        torreBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                torreBlancoMouseClicked(evt);
            }
        });

        alfilOscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alfilotro.png"))); // NOI18N
        alfilOscuro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        alfilOscuro.setPreferredSize(new java.awt.Dimension(68, 68));
        alfilOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alfilOscuroMouseClicked(evt);
            }
        });

        caballoOscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caballootro.png"))); // NOI18N
        caballoOscuro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        caballoOscuro.setPreferredSize(new java.awt.Dimension(68, 68));
        caballoOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caballoOscuroMouseClicked(evt);
            }
        });

        peonOscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peonotro.png"))); // NOI18N
        peonOscuro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        peonOscuro.setPreferredSize(new java.awt.Dimension(68, 68));
        peonOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peonOscuroMouseClicked(evt);
            }
        });

        reinaOscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reinaotra.png"))); // NOI18N
        reinaOscuro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reinaOscuro.setPreferredSize(new java.awt.Dimension(68, 68));
        reinaOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reinaOscuroMouseClicked(evt);
            }
        });

        reyOscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reyotro.png"))); // NOI18N
        reyOscuro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reyOscuro.setPreferredSize(new java.awt.Dimension(68, 68));
        reyOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reyOscuroMouseClicked(evt);
            }
        });

        torreOscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/torreotra.png"))); // NOI18N
        torreOscuro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        torreOscuro.setPreferredSize(new java.awt.Dimension(68, 68));
        torreOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                torreOscuroMouseClicked(evt);
            }
        });

        jLabel3.setText("AGERGAR PIEZAS");

        javax.swing.GroupLayout panelFichasLayout = new javax.swing.GroupLayout(panelFichas);
        panelFichas.setLayout(panelFichasLayout);
        panelFichasLayout.setHorizontalGroup(
            panelFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFichasLayout.createSequentialGroup()
                .addGroup(panelFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFichasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFichasLayout.createSequentialGroup()
                                .addComponent(alfilBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alfilOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFichasLayout.createSequentialGroup()
                                .addComponent(caballoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caballoOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFichasLayout.createSequentialGroup()
                                .addComponent(peonBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(peonOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFichasLayout.createSequentialGroup()
                                .addComponent(reinaBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reinaOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFichasLayout.createSequentialGroup()
                                .addComponent(reyBlanco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reyOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFichasLayout.createSequentialGroup()
                                .addComponent(torreBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(torreOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelFichasLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelFichasLayout.setVerticalGroup(
            panelFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFichasLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alfilBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alfilOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caballoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caballoOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peonBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peonOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reinaBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reinaOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reyOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(reyBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(torreBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(torreOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnJugar.setText("JUGAR");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        btnJuegoNuevo.setText("NUEVO JUEGO");
        btnJuegoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegoNuevoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LogJuego.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(LogJuego);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );

        etJugador.setText("JUGADOR:");

        labelJugador.setText("nombre_jugador");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("HISTORIAL DE JUEGO");

        jLabel1.setText("jLabel1");

        jButton2.setText("Abandonar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Solicitar Empate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Tablas por ley");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("2");
        jLabel4.setAlignmentX(2.0F);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("3");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("4");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("5");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("6");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("7");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("8");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addComponent(jLabel4)
                .addGap(55, 55, 55)
                .addComponent(jLabel5)
                .addGap(55, 55, 55)
                .addComponent(jLabel7)
                .addGap(55, 55, 55)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(55, 55, 55)
                .addComponent(jLabel10)
                .addGap(55, 55, 55)
                .addComponent(jLabel11)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(40, 509));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("A");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("B");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("C");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("D");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("F");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("G");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("H");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("E");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel18)
                .addGap(45, 45, 45)
                .addComponent(jLabel17)
                .addGap(45, 45, 45)
                .addComponent(jLabel16)
                .addGap(45, 45, 45)
                .addComponent(jLabel19)
                .addGap(44, 44, 44)
                .addComponent(jLabel15)
                .addGap(45, 45, 45)
                .addComponent(jLabel14)
                .addGap(46, 46, 46)
                .addComponent(jLabel13)
                .addGap(45, 45, 45)
                .addComponent(jLabel12)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TableroJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnJugar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnJuegoNuevo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etJugador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(labelJugador))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1)
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(61, 61, 61)))
                        .addComponent(panelFichas, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TableroJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnJugar)
                            .addComponent(btnJuegoNuevo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etJugador)
                            .addComponent(labelJugador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(21, 21, 21)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelFichas, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alfilBlancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alfilBlancoMouseClicked
        // TODO add your handling code here:
        activarDesactivarPiezas(alfilBlanco); 
        nombrePieza = "Alfil";
        equipo='B';
    }//GEN-LAST:event_alfilBlancoMouseClicked

    private void caballoBlancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caballoBlancoMouseClicked
        // TODO add your handling code here:
        activarDesactivarPiezas(caballoBlanco); 
        nombrePieza = "Caballo";
        equipo='B';
    }//GEN-LAST:event_caballoBlancoMouseClicked

    private void peonBlancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peonBlancoMouseClicked
        // TODO add your handling code here:
        activarDesactivarPiezas(peonBlanco); 
        nombrePieza = "Peon";
        equipo='B';
    }//GEN-LAST:event_peonBlancoMouseClicked

    private void reinaBlancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reinaBlancoMouseClicked
        // TODO add your handling code here:
        activarDesactivarPiezas(reinaBlanco);
        nombrePieza = "Reina";
        equipo='B';
    }//GEN-LAST:event_reinaBlancoMouseClicked

    private void reyBlancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reyBlancoMouseClicked
        // TODO add your handling code here:
        activarDesactivarPiezas(reyBlanco); 
        nombrePieza = "Rey";
        equipo='B';
    }//GEN-LAST:event_reyBlancoMouseClicked

    private void torreBlancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_torreBlancoMouseClicked
        // TODO add your handling code here:
        activarDesactivarPiezas(torreBlanco); 
        nombrePieza = "Torre";
        equipo='B';
    }//GEN-LAST:event_torreBlancoMouseClicked

    private void alfilOscuroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alfilOscuroMouseClicked
        // TODO add your handling code here:
        activarDesactivarPiezas(alfilOscuro); 
        nombrePieza = "Alfil";
        equipo='N';
    }//GEN-LAST:event_alfilOscuroMouseClicked

    private void caballoOscuroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caballoOscuroMouseClicked
        // TODO add your handling code here:
        activarDesactivarPiezas(caballoOscuro); 
        nombrePieza = "Caballo";
        equipo='N';
    }//GEN-LAST:event_caballoOscuroMouseClicked

    private void peonOscuroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peonOscuroMouseClicked
        // TODO add your handling code here:
        activarDesactivarPiezas(peonOscuro); 
        nombrePieza = "Peon";
        equipo='N';
    }//GEN-LAST:event_peonOscuroMouseClicked

    private void reinaOscuroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reinaOscuroMouseClicked
        // TODO add your handling code here:
        activarDesactivarPiezas(reinaOscuro); 
        nombrePieza = "Reina";
        equipo='N';
    }//GEN-LAST:event_reinaOscuroMouseClicked

    private void reyOscuroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reyOscuroMouseClicked
        // TODO add your handling code here:
        activarDesactivarPiezas(reyOscuro); 
        nombrePieza = "Rey";
        equipo='N';
    }//GEN-LAST:event_reyOscuroMouseClicked

    private void torreOscuroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_torreOscuroMouseClicked
        // TODO add your handling code here:
        activarDesactivarPiezas(torreOscuro); 
        nombrePieza = "Torre";
        equipo='N';
    }//GEN-LAST:event_torreOscuroMouseClicked

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        activarDesactivarPanelFichas(false);
        isActive=false;
        Tablero copiaTablero = ctrTablero.copiarTablero(tablero);
//        ControladorArbol ctrArbol = null;
//        Nodo nodoRaiz;
        ctrArbol.crearArbol(copiaTablero);
        Nodo nodoRaiz;
        nodoRaiz = ctrArbol.getNodoRaiz();
        nodoRaiz.setNivel(0);
        nodoRaiz.setIsMax(true);
        
        if(!turnoUsuario){
            if(colorJugador == 'B'){
                ctrArbol.calcularMovimientos(copiaTablero, 'N',nodoRaiz);
            }
            else{
                ctrArbol.calcularMovimientos(copiaTablero, 'B',nodoRaiz);
            }
            simularMovimientoComputador();
        }
        String descripcion = "--- SE INICIA EL JUEGO ---";
        agregarActividad("Sistema",descripcion); 
       
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnJuegoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegoNuevoActionPerformed
        // TODO add your handling code here:
        activarDesactivarPanelFichas(true);
        for(int i=0;i<8;i++){
            for(int j=0;j<8;j++){
                PintarPieza('B','N',i,j);
                tablero.getCasillas()[i][j]
                        .setPieza(ctrTablero.crearPieza(i,j,"NoPieza",'X'));
            }
        }
    }//GEN-LAST:event_btnJuegoNuevoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.finalizo = true;
        this.estadoJuego = "Has perdido por abandono";
        FinalJuego d = new FinalJuego(false, jugadas, this, estadoJuego);
        d.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        mostrar esto cuando la compu quiere empate mutuo
//        int respuesta = JOptionPane.showConfirmDialog(this, "Solicito empate mutuo, aceptas?", "Empate mutuo", 1);
//        System.out.println(respuesta);
        Random rand = new Random(); 
  
        // Generate random integers in range 0 to 1 
        int rand_int1 = rand.nextInt(2);
        if (rand_int1 == 1) {
            // no dar empate
           this.finalizo = true;
           this.estadoJuego = "Has empatado por acuerdo mutuo";
           JOptionPane.showMessageDialog(null, "Han aceptado el empate");
           FinalJuego d = new FinalJuego(false, jugadas, this, estadoJuego);
           d.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No ahorita, el juego continua");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // validar las fichas que hay
        // validar los movimientos hechos misma posicion 3 veces, últimos 5 movimientoa sin capturas
        // validar que no esta en jaque pero no tiene movimientos validos
        if (validarFichas()) {
            finalizo = true;
            estadoJuego = "Has empatado por ley, falta de fichas";
        } else {
            if (validarMovimientos()) {
                finalizo = true;
                estadoJuego = "Has empatado por ley, sin capturas";
            } else {
                if (validarTablasXNoJaque()) {
                    finalizo = true;
                    estadoJuego = "Has empatado por ley, sin jaque";
                }
            }
        }
        
        if (finalizo) {
            FinalJuego d = new FinalJuego(false, jugadas, this, estadoJuego);
            d.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

   private boolean validarFichas() {
       ArrayList<String> equipo1 = new ArrayList<>();
       ArrayList<String> equipo2 = new ArrayList<>();
       for (int i = 0; i < 8; i++) {
           for (int j = 0; j < 8; j++) {
               System.out.println(tablero.getCasillas()[i][j].pieza.getNombrePieza() + " " + tablero.getCasillas()[i][j].pieza.getEquipo());
               if (tablero.getCasillas()[i][j].pieza.getEquipo() == 'B') {
                   equipo1.add(tablero.getCasillas()[i][j].pieza.getNombrePieza());
               } else {
                   if (tablero.getCasillas()[i][j].pieza.getEquipo() == 'N') {
                      equipo2.add(tablero.getCasillas()[i][j].pieza.getNombrePieza());
                  }
               }
           }
       }
       if (equipo1.size() == 1 && equipo2.size() == 1) {
           if (equipo1.get(0).equals("Rey") && equipo2.get(0).equals("Rey")) {
               System.out.println("rey contra rey");
               return true;
           }
       }
       if (equipo1.size() == 1 && equipo2.size() == 2 || equipo2.size() == 1 && equipo1.size() == 2) {
           if (equipo1.indexOf("Rey") != -1 && 
                   ((equipo2.indexOf("Rey") != -1 && equipo2.indexOf("Alfil") != -1) || 
                   (equipo2.indexOf("Rey") != -1 && equipo2.indexOf("Caballo") != -1))) {
               System.out.println("rey contra dos");
               return true;
           }
           if (equipo2.indexOf("Rey") != -1 && 
                   ((equipo1.indexOf("Rey") != -1 && equipo1.indexOf("Alfil") != -1) || 
                   (equipo1.indexOf("Rey") != -1 && equipo1.indexOf("Caballo") != -1))) {
               System.out.println("rey contra dos");
               return true;
           }
       }
       
       if (equipo1.size() == 2 && equipo2.size() == 2) {
           if (equipo1.indexOf("Rey") != -1 && equipo1.indexOf("Alfil") != -1 && equipo2.indexOf("Alfil") != -1 && equipo2.indexOf("Rey") != -1) {
               System.out.println("rey y alfin x2");
               return true;
           }
       }
       return false;
   }
   
   private boolean validarMovimientos() {
       int contadorMovimientos = 0;
       for (int i = modeloActividad.getSize()-1; i > 0; i--) {
           System.out.println("validar " + modeloActividad.getElementAt(i));
           Pattern regex = Pattern.compile("\\b" + Pattern.quote("Movimiento") + "\\b", Pattern.CASE_INSENSITIVE);
           Matcher match = regex.matcher(modeloActividad.getElementAt(i)+"");
           if (match.find()) {
               System.out.println("tiene movimiento");
               contadorMovimientos++;
               if (contadorMovimientos == 5) {
                   return true;
               }
           }else {
               System.out.println("no tiene");
               contadorMovimientos = 0;
               return false;
           }
       }
       
       return false;
   }
   
   private boolean validarTablasXNoJaque() {
       return false;
   }
   
    public void activarDesactivarPiezas(JLabel pieza){
        if(isActive){
            Border borderDesactivo = BorderFactory.createLineBorder(Color.BLACK, 1);
            alfilBlanco.setBorder(borderDesactivo);
            caballoBlanco.setBorder(borderDesactivo);
            peonBlanco.setBorder(borderDesactivo);
            reinaBlanco.setBorder(borderDesactivo);
            reyBlanco.setBorder(borderDesactivo);
            torreBlanco.setBorder(borderDesactivo);
            //
            alfilOscuro.setBorder(borderDesactivo);
            caballoOscuro.setBorder(borderDesactivo);
            peonOscuro.setBorder(borderDesactivo);
            reinaOscuro.setBorder(borderDesactivo);
            reyOscuro.setBorder(borderDesactivo);
            torreOscuro.setBorder(borderDesactivo);
            //
            Border borderActivo = BorderFactory.createLineBorder(Color.YELLOW, 3);
            pieza.setBorder(borderActivo);
            ImageIcon = pieza.getIcon();
            isSelected = true;       
        }
    }
    
    public void activarDesactivarCasillas(JLabel escaque){
        Border borderDesactivo = BorderFactory.createLineBorder(Color.BLACK, 1);
        for (JLabel[] casilla : casillas) {
            for (int j = 0; j < casillas.length; j++) {
                casilla[j].setBorder(borderDesactivo);
            }
        }
        Border borderActivo = BorderFactory.createLineBorder(Color.YELLOW, 3);
        escaque.setBorder(borderActivo);  
    }
    
    public void activarPosiblesJugadas(){
        Border borderActivo = BorderFactory.createLineBorder(Color.BLUE, 3);
        Posicion mover;
        int movX;
        int movY;
        for(int i=0;i < movimientosPosibles.size();i++){
            mover = movimientosPosibles.get(i);
            movX = mover.getX();
            movY = mover.getY();
            casillas[movX][movY].setBorder(borderActivo);
        }
    }
    
    public void desactivarPosiblesJugadas(){
        Border borderDesactivo = BorderFactory.createLineBorder(Color.BLACK, 1);
        Posicion mover;
        int movX;
        int movY;
        for(int i=0;i < movimientosPosibles.size();i++){
            mover = movimientosPosibles.get(i);
            movX = mover.getX();
            movY = mover.getY();
            casillas[movX][movY].setBorder(borderDesactivo);
        }
    }
   
    /*
    *Panel de fichas: Agregar fichas manualmente
    */
    public void activarDesactivarPanelFichas(boolean opt){
        panelFichas.setVisible(opt); 
    }
    
    public void agregarJugador(String jugador,char colorJugador,boolean iniciarUsuario){
        this.Jugador = jugador;
        this.colorJugador=colorJugador;
        this.turnoUsuario = iniciarUsuario;
        labelJugador.setText(jugador);
    }
    
    public void generarTablero(){
        GridLayout tb = new GridLayout(TAMANIO,TAMANIO);
        boolean colorNegro = false;
        //nombrePieza= "NoPieza";
        for (int i = 0; i < casillas.length; i++) {
            for (int j = 0; j < casillas.length; j++) {
                casillas[i][j] = new JLabel();
                casillas[i][j].setOpaque(true);
                if(colorNegro){
                    casillas[i][j].setBackground(Color.black);
                }
                else{
                    casillas[i][j].setBackground(Color.white);
                } 
                colorNegro = !colorNegro;
                String X = Integer.toString(i);
                String Y = Integer.toString(j); 
                TableroJuego.add(casillas[i][j]);
                tablero.getCasillas()[i][j].setPieza(ctrTablero.crearPieza(i,j,"NoPieza",'X'));
                casillas[i][j].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        try {
                            agregarPieza(X,Y);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(TableroGUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    
                });
            }
            colorNegro = !colorNegro;
            TableroJuego.setLayout(tb);
            super.revalidate();
            super.repaint();
            
        }
        
    }
    
    public final void agregarPieza(String x,String y) throws InterruptedException{
        int i = Integer.parseInt(x);
        int j= Integer.parseInt(y);
        
        if(isSelected && isActive){
            casillas[i][j].setIcon(ImageIcon);
            tablero.getCasillas()[i][j].setPieza(ctrTablero.crearPieza(i,j,nombrePieza,equipo));
            String descripcion = "Se agrego "+nombrePieza;
            agregarActividad(Jugador,descripcion);   
        }
        else{
            activarDesactivarCasillas(casillas[i][j]);
            ctrTablero.moverPieza(tablero.getCasillas()[i][j].getPieza(),tablero);
            if(ctrTablero.getEstadoFinal()){
                if(ctrTablero.esMisma()){
                    desactivarPosiblesJugadas();
                }
                else{
                    Pieza piezaActiva = ctrTablero.getPiezaContenida();
                    simularMovimiento(piezaActiva);
                }
            }        
            else{
                movimientosPosibles = ctrTablero.movimientosPosibles(tablero.getCasillas()[i][j].getPieza(), tablero); 
                if(movimientosPosibles != null){
                    activarPosiblesJugadas();
                } 
            }
        }
    }
    
    
    public void simularMovimiento(Pieza pieza) throws InterruptedException{
        ArrayList<Posicion> movimientos;
        movimientos = ctrTablero.getMovimientos();
        int posInicialx = pieza.getPosicion().getX();
        int posInicialy = pieza.getPosicion().getY();
        if(movimientos.size()>0){
            char tipopieza = pieza.getCaracterPieza();
            char equipo = pieza.getEquipo();
            String nombrePieza = pieza.getNombrePieza();        
            PintarPieza('B','N',posInicialx,posInicialy);
            tablero.getCasillas()[posInicialx][posInicialy]
                    .setPieza(ctrTablero.crearPieza(posInicialx,posInicialy,"NoPieza",'X'));
            Posicion posTemporal;
            int posFinalx=0;
            int posFinaly=0;
            int tamMov = movimientos.size();
            for(int h=0;h<movimientos.size();h++){
                posTemporal = movimientos.get(h);
                posFinalx = posTemporal.getX();
                posFinaly = posTemporal.getY();
//                PintarPieza(equipo,tipopieza,posFinalx,posFinaly);    
//                PintarPieza('B','N',posFinalx,posFinaly);
            }
            String piezaComida = tablero.getCasillas()[posFinalx][posFinaly].getPieza().getNombrePieza();
            String descripcion;
            if(!"NoPieza".equals(piezaComida)){
                descripcion = "Cazar pieza: " + piezaComida;  
            }
            else{
                descripcion = " Movimiento = "+nombrePieza+
                    " ("+margen[posInicialx][posInicialy]+")"+"-"+"("+margen[posFinalx][posFinaly]+")";
            }
            PintarPieza(equipo,tipopieza,posFinalx,posFinaly);
            tablero.getCasillas()[posFinalx][posFinaly]
                    .setPieza(ctrTablero.crearPieza(posFinalx,posFinaly,pieza.getNombrePieza(),pieza.getEquipo()));
            ctrTablero.restablecerEstadoInicio();
            agregarActividad(Jugador,descripcion);
            intercambiarTurnoUsuario();
        }
    }
    


    
    public void simularMovimientoComputador(){
        solicitarEmpateLeyComputador();
        //System.out.println("Tablero que llega al simulador");
        //ctrTablero.imprimirTablero(copiaTablero);
        Nodo jugadaGenerada;
        Pieza pieza;
        Posicion posInicial;
        Posicion movimiento;
        jugadaGenerada = ctrArbol.ejecutarMovimiento();
        pieza = jugadaGenerada.getPieza();
        char tipopieza = pieza.getCaracterPieza();
        char equipoJuego = pieza.getEquipo();
        String nombrePieza = pieza.getNombrePieza();
        posInicial = jugadaGenerada.getPosInicial();
        int i = posInicial.getX() ;
        int j = posInicial.getY();
//        System.out.println(i + " " + j);
        PintarPieza('B','N',i,j);
        tablero.getCasillas()[i][j].setPieza(ctrTablero.crearPieza(i,j,"NoPieza",'X'));
        movimiento = jugadaGenerada.getPosFinal();
        int posFinalx;
        int posFinaly;
        posFinalx = movimiento.getX();
        posFinaly = movimiento.getY();
        String piezaComida = tablero.getCasillas()[posFinalx][posFinaly].getPieza().getNombrePieza();
        String descripcion;
        if(!"NoPieza".equals(piezaComida)){
            descripcion = "Cazar pieza: " + piezaComida;  
        }
        else{
            descripcion = " Movimiento = "+nombrePieza+
                " ("+margen[i][j]+")"+"-"+"("+margen[posFinalx][posFinaly]+")";
        }
        
        
        PintarPieza(equipoJuego,tipopieza,posFinalx,posFinaly);
        tablero.getCasillas()[posFinalx][posFinaly]
                    .setPieza(ctrTablero.crearPieza(posFinalx,posFinaly,pieza.getNombrePieza(),pieza.getEquipo()));
        ctrTablero.restablecerEstadoInicio();
        agregarActividad("Sistema",descripcion);
        intercambiarTurnoUsuario();
    }
         
    public void simularMovimiento() {

        try {
            jLabel1.setVisible(true);
            jLabel1.setSize(500, 500);
//            jLabel1.setIcon(new ImageIcon(getClass().getResource("/perdedor2.gif")));
            FinalJuego f = new FinalJuego(false, jugadas, this, estadoJuego);
            f.setVisible(true);
            System.out.println("ewerwaerw");
            //Se espera 1 segundo
            Thread.sleep(6000);
            System.out.println("ewerwaerw");
            jLabel1.setVisible(false);
            f.setVisible(false);
            repaint();
        } catch (InterruptedException ex) {
            Logger.getLogger(TableroGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }
    
//    private ArrayList<Integer> restarCampos(int inicio, int fin){
//        int diferencia = inicio - fin;
//        System.out.println("Diferencia: " + diferencia);
//        ArrayList<Integer> posiciones = new ArrayList<>();
//        for (int i = 0; i < diferencia; i++) {
//            System.out.println("inicio " + inicio + "fin " + fin);
//            inicio--;
//            posiciones.add(inicio);
//            
//        }
//        return posiciones;
//    }
//    
//    private ArrayList<Integer> sumarCampos(int inicio, int fin){
//        int diferencia = fin - inicio;
//        ArrayList<Integer> posiciones = new ArrayList<>();
//        for (int i = 0; i < diferencia; i++) {
//            inicio++;
//            posiciones.add(inicio);
//        }
//        return posiciones;
//    }
    
    public void intercambiarTurnoUsuario(){
        turnoUsuario = !turnoUsuario; 
        if(!turnoUsuario){
            Nodo nodoRaiz;
            ctrArbol.crearArbol(tablero);
            nodoRaiz = ctrArbol.getNodoRaiz();
            nodoRaiz.setNivel(0);
            nodoRaiz.setIsMax(true);
            if(colorJugador == 'B'){
                ctrArbol.calcularMovimientos(tablero, 'N',nodoRaiz);
            }
            else{
                ctrArbol.calcularMovimientos(tablero, 'B',nodoRaiz);
            }
            simularMovimientoComputador();
        }
    }
    
    public final void PintarPieza(char color, char piece, int x, int y){ 
        switch(piece)
        {
           case 'R' :
              nombrePieza = "Rey";
              if(color == 'B'){
                  ImageIcon = reyBlanco.getIcon();
              } else{
                  ImageIcon = reyOscuro.getIcon(); 
              }
              break;
           case 'D' :
              nombrePieza = "Reina";
              if(color == 'B'){
                  ImageIcon = reinaBlanco.getIcon(); 
              } else{
                  ImageIcon = reinaOscuro.getIcon(); 
              }
              break;
           case 'T' :
              nombrePieza = "Torre";
              if(color == 'B'){
                  ImageIcon = torreBlanco.getIcon(); 
              } else{
                  ImageIcon = torreOscuro.getIcon(); 
              }
              break;
           case 'A' :
              nombrePieza = "Alfil";
              if(color == 'B'){
                  ImageIcon = alfilBlanco.getIcon(); 
              } else{
                  ImageIcon = alfilOscuro.getIcon(); 
              }
              break;
           case 'C' :
              nombrePieza = "Caballo";
              if(color == 'B'){
                  ImageIcon = caballoBlanco.getIcon(); 
              } else{
                  ImageIcon = caballoOscuro.getIcon(); 
              }
              break;
           case 'P' :
              nombrePieza = "Peon";
              if(color == 'B'){
                  ImageIcon = peonBlanco.getIcon(); 
              } else{
                  ImageIcon = peonOscuro.getIcon(); 
              }
              break;
           case 'N' :
               nombrePieza = "NoPieza";
               ImageIcon = null;
               break;
           default : 
              // Declaraciones
        }
        casillas[x][y].setIcon(ImageIcon);
        tablero.getCasillas()[x][y].setPieza(ctrTablero.crearPieza(x,y,nombrePieza,color));
        super.revalidate();
        super.repaint();

    }
       
    public void agregarActividad(String usuario, String descripcion){
        jugadas += usuario + " " + descripcion + "\n";
        Actividad actividad = new Actividad(usuario,descripcion);
        modeloActividad.agregarActividad(actividad);
        
        if (!archivoResumen.exists()) {
            try {
                archivoResumen.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(TableroGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        FileWriter fw = null;
        try {
            fw = new FileWriter(archivoResumen.getAbsoluteFile(),true);
        } catch (IOException ex) {
            Logger.getLogger(TableroGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedWriter bw = new BufferedWriter(fw);
        String contenido = usuario+": "+descripcion;
        try {
            bw.write(contenido);
            bw.newLine();
        } catch (IOException ex) {
            Logger.getLogger(TableroGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(TableroGUI.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }
    
    public void eliminarActividad(int index){
        modeloActividad.eliminarActividad(index);
    }
    
    public void limpiarActividades(){
        modeloActividad.eliminarTodasActividades();
    }
    
    
    public void mensajeGanador(){
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableroGUI().setVisible(true);
            }
        });
    }

    
    private void solicitarEmpateLeyComputador() {
        if (validarFichas()) {
            finalizo = true;
            estadoJuego = "Has empatado por ley, falta de fichas";
        } else {
            if (validarMovimientos()) {
                finalizo = true;
                estadoJuego = "Has empatado por ley, sin capturas";
            } else {
                if (validarTablasXNoJaque()) {
                    finalizo = true;
                    estadoJuego = "Has empatado por ley, sin jaque";
                }
            }
        }
        
        if (finalizo) {
            JOptionPane.showMessageDialog(null, "Hay empate por ley");
            FinalJuego d = new FinalJuego(false, jugadas, this, estadoJuego);
            d.setVisible(true);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> LogJuego;
    private javax.swing.JPanel TableroJuego;
    private javax.swing.JLabel alfilBlanco;
    private javax.swing.JLabel alfilOscuro;
    private javax.swing.JButton btnJuegoNuevo;
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel caballoBlanco;
    private javax.swing.JLabel caballoOscuro;
    private javax.swing.JLabel etJugador;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelJugador;
    private javax.swing.JPanel panelFichas;
    private javax.swing.JLabel peonBlanco;
    private javax.swing.JLabel peonOscuro;
    private javax.swing.JLabel reinaBlanco;
    private javax.swing.JLabel reinaOscuro;
    private javax.swing.JLabel reyBlanco;
    private javax.swing.JLabel reyOscuro;
    private javax.swing.JLabel torreBlanco;
    private javax.swing.JLabel torreOscuro;
    // End of variables declaration//GEN-END:variables

}
