/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajedrezia;

import java.awt.Color;

/**
 *
 * @author Joaquin
 */
public class Casilla extends javax.swing.JPanel {

    /**
     * Creates new form Casilla
     */
    public Casilla() {
        initComponents();
    }
    
    
    public void setColor(int codColor){
        if (codColor == 1) {
            Casilla.setBackground(Color.WHITE);
        }
        else
        {
            Casilla.setBackground(Color.BLACK);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Casilla = new javax.swing.JPanel();

        Casilla.setBackground(new java.awt.Color(255, 255, 255));
        Casilla.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout CasillaLayout = new javax.swing.GroupLayout(Casilla);
        Casilla.setLayout(CasillaLayout);
        CasillaLayout.setHorizontalGroup(
            CasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        CasillaLayout.setVerticalGroup(
            CasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Casilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Casilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Casilla;
    // End of variables declaration//GEN-END:variables
}
