/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajedrezia;

import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JLabel;

/**
 *
 * @author Joaquin
 */
public class Tablero extends javax.swing.JFrame {

    private JLabel escaques[][];
    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tablero = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tablero.setBackground(new java.awt.Color(0, 153, 153));
        Tablero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Tablero.setAlignmentX(0.0F);
        Tablero.setAlignmentY(0.0F);
        Tablero.setAutoscrolls(true);
        Tablero.setPreferredSize(new java.awt.Dimension(800, 800));
        Tablero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TableroLayout = new javax.swing.GroupLayout(Tablero);
        Tablero.setLayout(TableroLayout);
        TableroLayout.setHorizontalGroup(
            TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        TableroLayout.setVerticalGroup(
            TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tablero, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tablero, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    public void generarTablero(){
        GridLayout tb = new GridLayout(8,8);
        
        
        boolean colorNegro = false;
        escaques = new JLabel[8][8];
        for (JLabel[] escaque : escaques) {
            for (int j = 0; j < escaque.length; j++) {
                escaque[j] = new JLabel();
                escaque[j].setOpaque(true);
//                escaques[i][j].setText(i+","+j);
                if (colorNegro) {
                    escaque[j].setBackground(Color.black);
                } else {
                    escaque[j].setBackground(Color.white);
                }
                colorNegro = !colorNegro;
                Tablero.add(escaque[j]);
                //escaques[i][j].addMouseListener(
                //new ManejadorDeClics(miAjedrez.getTablero().getCasillas()[j][7-i]));
            }
            colorNegro = !colorNegro;
            Tablero.setLayout(tb);
            super.revalidate();
            super.repaint();
        }
    }
    
    private void TableroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableroMouseClicked
        // TODO add your handling code here:
        //Dibujar t = new Dibujar(Tablero.getGraphics(), this.Tablero.getWidth());
        GridLayout tb = new GridLayout(8,8);
        
        
        boolean colorNegro = false;
        escaques = new JLabel[8][8];
        for (JLabel[] escaque : escaques) {
            for (int j = 0; j < escaque.length; j++) {
                escaque[j] = new JLabel();
                escaque[j].setOpaque(true);
//                escaques[i][j].setText(i+","+j);
                if (colorNegro) {
                    escaque[j].setBackground(Color.black);
                } else {
                    escaque[j].setBackground(Color.white);
                }
                colorNegro = !colorNegro;
                Tablero.add(escaque[j]);
                //escaques[i][j].addMouseListener(
                //new ManejadorDeClics(miAjedrez.getTablero().getCasillas()[j][7-i]));
            }
            colorNegro = !colorNegro;
            Tablero.setLayout(tb);
            super.revalidate();
            super.repaint();
        }
            
    }//GEN-LAST:event_TableroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Tablero;
    // End of variables declaration//GEN-END:variables
}
